output = "dao"
pkgname = "dao"
no-tests = true
add-enum-types = true
no-hooks = true

[psql]
dbname = "pro-posal"
host   = "localhost"
port   = 5432
user   = "admin"
pass   = "Aa123456"
schema = "public"
sslmode = "disable"