// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dao

var TableNames = struct {
	Categories        string
	Companies         string
	ContractTemplates string
	GooseDBVersion    string
	Offers            string
	Permissions       string
	Session           string
	Users             string
}{
	Categories:        "categories",
	Companies:         "companies",
	ContractTemplates: "contract_templates",
	GooseDBVersion:    "goose_db_version",
	Offers:            "offers",
	Permissions:       "permissions",
	Session:           "session",
	Users:             "users",
}
