// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("CategoryToCompanyUsingCompany", testCategoryToOneCompanyUsingCompany)
	t.Run("CompanyToUserUsingContact", testCompanyToOneUserUsingContact)
	t.Run("ContractTemplateToCompanyUsingCompany", testContractTemplateToOneCompanyUsingCompany)
	t.Run("OfferToCompanyUsingCompany", testOfferToOneCompanyUsingCompany)
	t.Run("OfferToContractTemplateUsingContractTemplate", testOfferToOneContractTemplateUsingContractTemplate)
	t.Run("OfferToUserUsingCreatedByUser", testOfferToOneUserUsingCreatedByUser)
	t.Run("OfferToUserUsingCustomer", testOfferToOneUserUsingCustomer)
	t.Run("PermissionToCompanyUsingCompany", testPermissionToOneCompanyUsingCompany)
	t.Run("PermissionToUserUsingUser", testPermissionToOneUserUsingUser)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("CompanyToCategories", testCompanyToManyCategories)
	t.Run("CompanyToContractTemplates", testCompanyToManyContractTemplates)
	t.Run("CompanyToOffers", testCompanyToManyOffers)
	t.Run("CompanyToPermissions", testCompanyToManyPermissions)
	t.Run("ContractTemplateToOffers", testContractTemplateToManyOffers)
	t.Run("UserToContactCompanies", testUserToManyContactCompanies)
	t.Run("UserToCreatedByOffers", testUserToManyCreatedByOffers)
	t.Run("UserToCustomerOffers", testUserToManyCustomerOffers)
	t.Run("UserToPermissions", testUserToManyPermissions)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("CategoryToCompanyUsingCategories", testCategoryToOneSetOpCompanyUsingCompany)
	t.Run("CompanyToUserUsingContactCompanies", testCompanyToOneSetOpUserUsingContact)
	t.Run("ContractTemplateToCompanyUsingContractTemplates", testContractTemplateToOneSetOpCompanyUsingCompany)
	t.Run("OfferToCompanyUsingOffers", testOfferToOneSetOpCompanyUsingCompany)
	t.Run("OfferToContractTemplateUsingOffers", testOfferToOneSetOpContractTemplateUsingContractTemplate)
	t.Run("OfferToUserUsingCreatedByOffers", testOfferToOneSetOpUserUsingCreatedByUser)
	t.Run("OfferToUserUsingCustomerOffers", testOfferToOneSetOpUserUsingCustomer)
	t.Run("PermissionToCompanyUsingPermissions", testPermissionToOneSetOpCompanyUsingCompany)
	t.Run("PermissionToUserUsingPermissions", testPermissionToOneSetOpUserUsingUser)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("CompanyToCategories", testCompanyToManyAddOpCategories)
	t.Run("CompanyToContractTemplates", testCompanyToManyAddOpContractTemplates)
	t.Run("CompanyToOffers", testCompanyToManyAddOpOffers)
	t.Run("CompanyToPermissions", testCompanyToManyAddOpPermissions)
	t.Run("ContractTemplateToOffers", testContractTemplateToManyAddOpOffers)
	t.Run("UserToContactCompanies", testUserToManyAddOpContactCompanies)
	t.Run("UserToCreatedByOffers", testUserToManyAddOpCreatedByOffers)
	t.Run("UserToCustomerOffers", testUserToManyAddOpCustomerOffers)
	t.Run("UserToPermissions", testUserToManyAddOpPermissions)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}
